'use strict';let l=[],m=0,n=0;document.addEventListener("mousemove",function(b){m=b.clientX-q.offsetLeft;n=b.clientY-q.offsetTop+window.pageYOffset},!1);document.addEventListener("mousedown",function(b){l[b.button]=r},!1);document.addEventListener("mouseup",function(b){l[b.button]=0},!1);let t=Math.sqrt,aa=Math.cos,ba=Math.sin,u=Math.min;function v(){return 2*Math.random()-1}let w=[0,0,0,0],x=[0,0,0,0],y=[0,0,0,0],z=[0,0,0,0],A=[0,0,0,0],ca=[0,0,0,0],B=[0,0,0,0],C=[0,0,0,0];
function D(b,a,c){return b[0]=a,b[1]=c,b}function E(b,a,c){return b[0]=a[0]+c[0],b[1]=a[1]+c[1],b}function F(b,a,c,d){b[0]=a[0]+c[0]*d;b[1]=a[1]+c[1]*d}function G(b,a,c){return b[0]=a[0]-c[0],b[1]=a[1]-c[1],b}function H(b,a){return b[0]*a[0]+b[1]*a[1]}function I(b,a){return b[0]*a[1]-b[1]*a[0]}function J(b,a,c){return b[0]=-a[1]*c,b[1]=a[0]*c,b}function K(b,a,c){return b[0]=a[0]*c,b[1]=a[1]*c,b}function L(b,a){b[0]=a[0];b[1]=a[1]}function da(b,a){return b[0]=-a[0],b[1]=-a[1],b}
function M(b,a,c){b[0]=a[0]*c[0]-a[1]*c[1];b[1]=a[1]*c[0]+a[0]*c[1];return b}function N(b,a,c){b[0]=a[0]*c[0]+a[1]*c[1];b[1]=-a[1]*c[0]+a[0]*c[1];return b}
function O(b){a:{var a=0;var c=D(x,0,-1);var d;for(d=1;d<b.length;++d)b[d][0]>b[a][0]&&(a=d);var e=b[0];a=b[a];L(A,e);L(e,a);L(a,A);for(e=1;;++e){a=-1;for(d=e;d<b.length;++d)0<I(G(w,b[d],b[e-1]),c)&&(L(c,w),a=d);if(-1==a){c=e;break a}d=b[e];a=b[a];L(A,d);L(d,a);L(a,A);G(c,b[0],b[e])}}b.length=c;a=0;d=b[b.length-1];let g=b[0],h=D(w,0,0);for(c=0;c<b.length;++c,d=g,g=b[c])e=I(d,g),a+=e,F(h,h,d,e),F(h,h,g,e);K(h,h,1/(3*a));for(c=0;c<b.length;++c)G(b[c],b[c],h);e=0;let f;for(c=0;c<b.length;++c)(f=H(b[c],
b[c]))>e&&(e=f);b.r=t(e);b.a=.5*a;return b}O([[-20,-10],[20,-10],[20,10],[-20,10]]);let fa=O([[-12,-12],[12,-12],[12,12],[-12,12]]);O([[10,0],[7,7],[0,10],[-7,7],[-10,0],[-7,-7],[0,-10],[7,-7]]);let P=[],R=[[0,1,100]],ha=[0,-.1],S=[];function T(b,a,c){E(b.c,b.c,c);b.f+=.5/(b.r*b.r)*I(a,c)}function ia(b,a,c){let d,e=b[0],g=H(a,b[0]);for(let h=1;h<b.length;++h)(d=H(a,b[h]))<g&&(g=d,e=b[h]);c[2]=g;return e}
function ja(b,a,c,d){let e=N(w,a.d,c.d),g=N(x,a.d,G(y,c.p,a.p));for(let k=0,p=c.b[c.b.length-1],Q=c.b[0];k<c.b.length;++k,p=Q,Q=c.b[k]){var h=D(y,Q[1]-p[1],p[0]-Q[0]),f=M(z,e,h);let na=ia(a.b,f,z),ea=z[2]-(H(h,p)+H(f,g));if(0<=ea)return 1;h=K(y,f,ea/H(h,h));f=H(h,h);f<d*d&&(f=t(f),d=-f,K(A,h,1/-f),L(b,na))}return d}let r=0,ka=0,U=void 0;
function la(){V.setTransform(1,0,0,1,0,0);V.fillStyle="#c44";V.fillRect(0,0,q.width,q.height);V.fillStyle="#0f0";V.setTransform(1,0,0,-1,0,0);var b=m,a=-n;if(l[0]==r)a:{var c=D(w,b,a);for(var d=0;d<P.length;++d){var e=P[d],g=G(x,c,e.p),h=N(y,e.d,g);g=e.b;for(var f=g[g.length-1],k=g[0],p=0;p<g.length&&0>I(G(ca,h,f),G(A,k,f));++p,f=k,k=g[p]);if(g=p==g.length){c=e;b=D([],b,a);a=G(x,b,c.p);b={h:c,p:b,r:N([],c.d,a)};S.push(b);U=b;break a}}U=void 0}else void 0!==U&&(l[0]?D(U.p,b,a):(b=S.indexOf(U),-1<b&&
S.splice(b,1),U=void 0));for(b=0;b<S.length;++b)a=S[b],c=a.h,d=M(w,c.d,a.r),e=J(x,d,c.f),E(e,e,c.c),g=E(y,d,c.p),G(g,a.p,g),G(e,g,e),K(e,e,.5),T(c,d,e);for(b=0;b<P.length;++b)a=P[b],E(a.p,a.p,a.c),K(a.c,a.c,.99),0!==a.a&&E(a.c,a.c,ha),a.g+=a.f,D(a.d,aa(a.g),ba(a.g));for(d=0;d<P.length-1;++d)for(e=d+1;e<P.length;++e)b=g=void 0,a=P[d],c=P[e],0!=a.a+c.a&&(G(w,c.p,a.p),H(w,w)>=(c.r+a.r)*(c.r+a.r)||(f=ca,0<=(g=ja(f,c,a,-99999))||0<=(b=ja(f,a,c,g))||(b>g?(M(C,a.d,f),E(C,C,a.p),M(B,a.d,A),da(B,B)):(M(C,
c.d,f),E(C,C,c.p),M(B,c.d,A)),g=G(w,C,a.p),h=G(x,C,c.p),f=E(y,J(y,g,a.f),a.c),k=E(z,J(z,h,c.f),c.c),f=G(y,k,f),p=H(B,f),k=-u(0,p)-.25*b,F(f,f,B,-p),p=.1>H(f,f)?1:.05,k=K(z,B,k),F(k,k,f,-p),a.a&&c.a?(f=a.a/(c.a+a.a),T(a,g,K(y,k,f-1)),T(c,h,K(y,k,f)),F(a.p,a.p,B,.5*+b),F(c.p,c.p,B,.5*-b)):a.a?(T(a,g,da(y,k)),F(a.p,a.p,B,+b)):(T(c,h,k),F(c.p,c.p,B,-b)))));for(b=0;b<P.length;++b)if(a=P[b],0!==a.a)for(c=0;c<R.length;++c)d=R[c],e=H(a.p,d)+d[2],e<a.r&&(N(w,a.d,d),g=ia(a.b,w,x),e=x[2]+e,0<=e||(g=M(w,a.d,
g),h=J(x,g,a.f),E(h,h,a.c),k=H(d,h),f=.5*-u(k,0)-.1*e,F(h,h,d,-k),k=.1>H(h,h)?1:.05,f=K(y,d,f),F(f,f,h,-k),T(a,g,f),F(a.p,a.p,d,.7*-e)));V.beginPath();for(b=0;b<S.length;++b)a=S[b].p,V.moveTo(a[0]-2,a[1]-2),V.lineTo(a[0]+2,a[1]+2),V.moveTo(a[0]+2,a[1]-2),V.lineTo(a[0]-2,a[1]+2);V.stroke();V.save();V.strokeStyle="white";V.fillStyle="#993333";for(b=0;b<P.length;++b){a=P[b];c=a.b.length;V.save();V.transform(a.d[0],a.d[1],-a.d[1],a.d[0],a.p[0],a.p[1]);V.beginPath();for(d=0;d<c;++d)V.lineTo(a.b[d][0],
a.b[d][1]);V.fill();V.restore()}++ka;++r;requestAnimationFrame(la,q)}function ma(){q.width=q.clientWidth;q.height=q.clientHeight;R[0]=[0,1,q.height-2];R[1]=[1,0,-2];R[2]=[-1,0,q.width-2];R[3]=[0,-1,-2]}let q=$("cv"),V=q.getContext("2d");window.addEventListener("resize",ma,!1);ma();P=[];
for(let b=1;16>=b;++b){var oa;{let d={p:[0,0],c:[0,0],d:[1,0],g:0,f:0,i:[0,0],locked:!1};var W=d,X=fa;W.b=X;W.r=X.r;W.a=X.a;P.push(d);oa=d}let a=oa;D(a.p,50*b,100*v()+-100);D(a.c,v(),v());let c=[];for(let d=0;16>d;++d)c[d]=[35*v(),35*v()];c=O(c);var Y=a,Z=c;Y.b=Z;Y.r=Z.r;Y.a=Z.a}requestAnimationFrame(la,q);
